//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserWar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserWar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string resB {
            get {
                return ResourceManager.GetString("resB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string resClose {
            get {
                return ResourceManager.GetString("resClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        internal static string resDownload {
            get {
                return ResourceManager.GetString("resDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        internal static string resDownloading {
            get {
                return ResourceManager.GetString("resDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.
        /// </summary>
        internal static string resErrorOccured {
            get {
                return ResourceManager.GetString("resErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл успешно загружен.
        /// </summary>
        internal static string resFileDownloadedSuccessfully {
            get {
                return ResourceManager.GetString("resFileDownloadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла.
        /// </summary>
        internal static string resFileName {
            get {
                return ResourceManager.GetString("resFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер файла.
        /// </summary>
        internal static string resFileSize {
            get {
                return ResourceManager.GetString("resFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ходе работы программы {0} произошла критическая ошибка &quot;{1}&quot;, приложение будет закрыто. Было создано 2 файла отчета об ошибке {2} и {3}..
        /// </summary>
        internal static string resfmtAppCrashedWithStackTrace {
            get {
                return ResourceManager.GetString("resfmtAppCrashedWithStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить файл:
        ///{0}.
        /// </summary>
        internal static string resfmtCantDownloadFile {
            get {
                return ResourceManager.GetString("resfmtCantDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON объект.
        /// </summary>
        internal static string resJsonObject {
            get {
                return ResourceManager.GetString("resJsonObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string resKB {
            get {
                return ResourceManager.GetString("resKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файла.
        /// </summary>
        internal static string resLoadFile {
            get {
                return ResourceManager.GetString("resLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестовое задание.
        /// </summary>
        internal static string resMainWndTitle {
            get {
                return ResourceManager.GetString("resMainWndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string resMB {
            get {
                return ResourceManager.GetString("resMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ходе работы программы {0} произошла критическая ошибка &quot;{1}&quot;, приложение будет закрыто. Был создан файл отчета об ошибке {2}..
        /// </summary>
        internal static string resmsgfmtAppCrashed {
            get {
                return ResourceManager.GetString("resmsgfmtAppCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воспроизвести.
        /// </summary>
        internal static string resPlayFile {
            get {
                return ResourceManager.GetString("resPlayFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл загружен.
        /// </summary>
        internal static string resSoundLoaded {
            get {
                return ResourceManager.GetString("resSoundLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звуки.
        /// </summary>
        internal static string resSounds {
            get {
                return ResourceManager.GetString("resSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес файла.
        /// </summary>
        internal static string resUrlAddress {
            get {
                return ResourceManager.GetString("resUrlAddress", resourceCulture);
            }
        }
    }
}
