//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserWar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserWar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точность.
        /// </summary>
        internal static string resAccuracy {
            get {
                return ResourceManager.GetString("resAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точность должна быть числом в диапазоне от 0% до 100%.
        /// </summary>
        internal static string resAccuracyMustBeFrom0To1 {
            get {
                return ResourceManager.GetString("resAccuracyMustBeFrom0To1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string resB {
            get {
                return ResourceManager.GetString("resB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string resCancel {
            get {
                return ResourceManager.GetString("resCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить скриншот программы.
        /// </summary>
        internal static string resCantCreateScreen {
            get {
                return ResourceManager.GetString("resCantCreateScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось опубликовать сообщение.
        /// </summary>
        internal static string resCantPublicatePost {
            get {
                return ResourceManager.GetString("resCantPublicatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string resClose {
            get {
                return ResourceManager.GetString("resClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        internal static string resDownload {
            get {
                return ResourceManager.GetString("resDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        internal static string resDownloading {
            get {
                return ResourceManager.GetString("resDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование игрока.
        /// </summary>
        internal static string resEditPlayer {
            get {
                return ResourceManager.GetString("resEditPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.
        /// </summary>
        internal static string resErrorOccured {
            get {
                return ResourceManager.GetString("resErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл успешно загружен.
        /// </summary>
        internal static string resFileDownloadedSuccessfully {
            get {
                return ResourceManager.GetString("resFileDownloadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя файла.
        /// </summary>
        internal static string resFileName {
            get {
                return ResourceManager.GetString("resFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер файла.
        /// </summary>
        internal static string resFileSize {
            get {
                return ResourceManager.GetString("resFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ходе работы программы {0} произошла критическая ошибка &quot;{1}&quot;, приложение будет закрыто. Было создано 2 файла отчета об ошибке {2} и {3}..
        /// </summary>
        internal static string resfmtAppCrashedWithStackTrace {
            get {
                return ResourceManager.GetString("resfmtAppCrashedWithStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить файл:
        ///{0}.
        /// </summary>
        internal static string resfmtCantDownloadFile {
            get {
                return ResourceManager.GetString("resfmtCantDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить документ PDF
        ///&quot;{0}&quot;.
        /// </summary>
        internal static string resfmtPDFFileDontSaved {
            get {
                return ResourceManager.GetString("resfmtPDFFileDontSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ PDF &quot;{0}&quot; успешно сохранён.
        /// </summary>
        internal static string resfmtPDFFileSavedSuccessfully {
            get {
                return ResourceManager.GetString("resfmtPDFFileSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись успешно опубликована в группе &quot;{0}&quot;..
        /// </summary>
        internal static string resfmtPostPublishedSuccessfully {
            get {
                return ResourceManager.GetString("resfmtPostPublishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата проведения.
        /// </summary>
        internal static string resGameDate {
            get {
                return ResourceManager.GetString("resGameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название игры.
        /// </summary>
        internal static string resGameName {
            get {
                return ResourceManager.GetString("resGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игры.
        /// </summary>
        internal static string resGames {
            get {
                return ResourceManager.GetString("resGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы.
        /// </summary>
        internal static string resGroups {
            get {
                return ResourceManager.GetString("resGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        internal static string resInformation {
            get {
                return ResourceManager.GetString("resInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON объект.
        /// </summary>
        internal static string resJsonObject {
            get {
                return ResourceManager.GetString("resJsonObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string resKB {
            get {
                return ResourceManager.GetString("resKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файла.
        /// </summary>
        internal static string resLoadFile {
            get {
                return ResourceManager.GetString("resLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестовое задание.
        /// </summary>
        internal static string resMainWndTitle {
            get {
                return ResourceManager.GetString("resMainWndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string resMB {
            get {
                return ResourceManager.GetString("resMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ходе работы программы {0} произошла критическая ошибка &quot;{1}&quot;, приложение будет закрыто. Был создан файл отчета об ошибке {2}..
        /// </summary>
        internal static string resmsgfmtAppCrashed {
            get {
                return ResourceManager.GetString("resmsgfmtAppCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Имя игрока&quot; не должно быть пустым.
        /// </summary>
        internal static string resNameCouldNotBeEmpty {
            get {
                return ResourceManager.GetString("resNameCouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string resPercent {
            get {
                return ResourceManager.GetString("resPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игрок.
        /// </summary>
        internal static string resPlayer {
            get {
                return ResourceManager.GetString("resPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя игрока.
        /// </summary>
        internal static string resPlayerName {
            get {
                return ResourceManager.GetString("resPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество игроков.
        /// </summary>
        internal static string resPlayersCount {
            get {
                return ResourceManager.GetString("resPlayersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воспроизвести.
        /// </summary>
        internal static string resPlayFile {
            get {
                return ResourceManager.GetString("resPlayFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликовать.
        /// </summary>
        internal static string resPublicate {
            get {
                return ResourceManager.GetString("resPublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        internal static string resRating {
            get {
                return ResourceManager.GetString("resRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг должен быть положительным числом.
        /// </summary>
        internal static string resRatingMustBeNotNegative {
            get {
                return ResourceManager.GetString("resRatingMustBeNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string resSave {
            get {
                return ResourceManager.GetString("resSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документы PDF|*.pdf.
        /// </summary>
        internal static string resSavePDFFilter {
            get {
                return ResourceManager.GetString("resSavePDFFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выстрелы.
        /// </summary>
        internal static string resShots {
            get {
                return ResourceManager.GetString("resShots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число выстрелов должно быть неотрицательным числом.
        /// </summary>
        internal static string resShotsMustBeNotNegative {
            get {
                return ResourceManager.GetString("resShotsMustBeNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл загружен.
        /// </summary>
        internal static string resSoundLoaded {
            get {
                return ResourceManager.GetString("resSoundLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звуки.
        /// </summary>
        internal static string resSounds {
            get {
                return ResourceManager.GetString("resSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как PDF.
        /// </summary>
        internal static string resToPDF {
            get {
                return ResourceManager.GetString("resToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубликовать в ВК.
        /// </summary>
        internal static string resToVk {
            get {
                return ResourceManager.GetString("resToVk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес файла.
        /// </summary>
        internal static string resUrlAddress {
            get {
                return ResourceManager.GetString("resUrlAddress", resourceCulture);
            }
        }
    }
}
